# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wodLoop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from LoteryWod import *


class WodLoop_Ui_Dialog(QtWidgets.QMainWindow):

    def __init__(self, team, teamName, group, confirmSuit, confirmBcardList):
        super(WodLoop_Ui_Dialog, self).__init__()
        self.teamConfigValue = team
        self.teamNameConfig = teamName
        self.confirmSuit = confirmSuit
        self.confirmBcardList = confirmBcardList
        self.group = group
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(482, 300)

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(350, 230, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.pickWod)

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(382, 7, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 31, 31))
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 40, 171, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(250, 40, 41, 31))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(290, 40, 48, 24))
        self.spinBox.setObjectName("spinBox")
        self.label_2.setVisible(bool(self.teamConfigValue[0]))
        self.textBrowser_2.setVisible(bool(self.teamConfigValue[0]))
        self.spinBox.setVisible(bool(self.teamConfigValue[0]))
        self.label.setVisible(bool(self.teamConfigValue[0]))

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 31, 31))
        self.label_3.setObjectName("label_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(50, 90, 171, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setGeometry(QtCore.QRect(290, 90, 48, 24))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(250, 90, 41, 31))
        self.label_7.setObjectName("label_7")
        self.label_3.setVisible(bool(self.teamConfigValue[1]))
        self.textBrowser_3.setVisible(bool(self.teamConfigValue[1]))
        self.label_7.setVisible(bool(self.teamConfigValue[1]))
        self.spinBox_2.setVisible(bool(self.teamConfigValue[1]))

        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 31, 31))
        self.label_4.setObjectName("label_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(50, 140, 171, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.spinBox_3 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_3.setGeometry(QtCore.QRect(290, 140, 48, 24))
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(250, 140, 41, 31))
        self.label_8.setObjectName("label_8")
        self.label_4.setVisible(bool(self.teamConfigValue[2]))
        self.textBrowser_4.setVisible(bool(self.teamConfigValue[2]))
        self.label_8.setVisible(bool(self.teamConfigValue[2]))
        self.spinBox_3.setVisible(bool(self.teamConfigValue[2]))

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 31, 31))
        self.label_5.setObjectName("label_5")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_5.setGeometry(QtCore.QRect(50, 190, 171, 31))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.spinBox_4 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_4.setGeometry(QtCore.QRect(290, 190, 48, 24))
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(250, 190, 41, 31))
        self.label_9.setObjectName("label_9")
        self.label_5.setVisible(bool(self.teamConfigValue[3]))
        self.textBrowser_5.setVisible(bool(self.teamConfigValue[3]))
        self.label_9.setVisible(bool(self.teamConfigValue[3]))
        self.spinBox_4.setVisible(bool(self.teamConfigValue[3]))

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 31, 31))
        self.label_6.setObjectName("label_6")
        self.textBrowser_6 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_6.setGeometry(QtCore.QRect(50, 240, 171, 31))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(250, 240, 41, 31))
        self.label_10.setObjectName("label_10")
        self.spinBox_5 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_5.setGeometry(QtCore.QRect(290, 240, 48, 24))
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_6.setVisible(bool(self.teamConfigValue[4]))
        self.textBrowser_6.setVisible(bool(self.teamConfigValue[4]))
        self.label_10.setVisible(bool(self.teamConfigValue[4]))
        self.spinBox_5.setVisible(bool(self.teamConfigValue[4]))

        self.textBrowser_7 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_7.setGeometry(QtCore.QRect(190, 6, 121, 31))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(360, 60, 91, 141))
        self.label_11.setObjectName("label_11")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_2.setText(_translate("Dialog", "重开一局"))

        if self.group == 5:
            groupName = ['A', 'B', 'C', 'D', 'E']
        else:
            groupName = ['红桃', '黑桃', '草花', '方片', 'null']

        self.label_2.setText(_translate("Dialog", groupName[0]))
        self.label_3.setText(_translate("Dialog", groupName[1]))
        self.label_4.setText(_translate("Dialog", groupName[2]))
        self.label_5.setText(_translate("Dialog", groupName[3]))
        self.label_6.setText(_translate("Dialog", groupName[4]))

        self.textBrowser_7.setHtml(_translate("Dialog",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">LotteryWod</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "分数"))
        self.label_7.setText(_translate("Dialog", "分数"))
        self.label_8.setText(_translate("Dialog", "分数"))
        self.label_9.setText(_translate("Dialog", "分数"))
        self.label_10.setText(_translate("Dialog", "分数"))
        # self.label_11.setText(_translate("Dialog", "TextLabel"))

        picPath = '../Resources/PokerPictures/pokerBack.jpg'
        print(picPath)
        pic = QtGui.QPixmap(picPath)
        self.label_11.setPixmap(pic)
        self.label_11.setScaledContents(True)

        self.pushButton.setText(_translate("Dialog", "抽取一个wod"))
        self.setEveryTeamName()

    def pickWod(self):
        luckyWod = selectWod()
        print("lucky wod is ", luckyWod)
        picPath = '../Resources/PokerPictures/' + luckyWod + '.jpg'
        pic = QtGui.QPixmap(picPath)
        self.label_11.setPixmap(pic)
        self.label_11.setScaledContents(True)
        return luckyWod

    def setEveryTeamName(self):
        self.textBrowser_2.setText(self.teamNameConfig[0])
        self.textBrowser_3.setText(self.teamNameConfig[1])
        self.textBrowser_4.setText(self.teamNameConfig[2])
        self.textBrowser_5.setText(self.teamNameConfig[3])
        self.textBrowser_6.setText(self.teamNameConfig[4])
