# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GroupSplitMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import ui
import time
from LoteryWod import *
from PyQt5 import QtCore, QtGui, QtWidgets


def cardUpdateDeck(removeCard):
    athleteDeck = AthleteDeck()
    athleteDeck.remove(removeCard)
    print(athleteDeck)


class Ui_GroupSplitMainWindow(QtWidgets.QMainWindow):
    switch_window_WodLoop = QtCore.pyqtSignal(object, object, object)
    switch_window_AthleteConfirm = QtCore.pyqtSignal(object, object)

    def __init__(self, team, group, teamEveryNum, confirmAction, confirmBcardList):
        super(Ui_GroupSplitMainWindow, self).__init__()
        self.teamConfigValue = team
        self.group = group
        self.groupTemp = group
        self.teamEveryNum = teamEveryNum
        self.groupName = []
        self.teamNameConfig = ['', '', '', '', '']
        self.confirmAction = confirmAction
        self.confirmBcardList = confirmBcardList
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, GroupSplitMainWindow):
        GroupSplitMainWindow.setObjectName("GroupSplitMainWindow")
        GroupSplitMainWindow.resize(844, 567)
        self.centralwidgetWhole = QtWidgets.QWidget(GroupSplitMainWindow)
        self.centralwidgetWhole.setObjectName("centralwidgetWhole")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidgetWhole)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayoutWhole = QtWidgets.QGridLayout()
        self.gridLayoutWhole.setObjectName("gridLayoutWhole")
        self.labelTitle = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setMinimumSize(QtCore.QSize(0, 50))
        self.labelTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayoutWhole.addWidget(self.labelTitle, 0, 0, 1, 2)
        self.formLayouTeam = QtWidgets.QFormLayout()
        self.formLayouTeam.setObjectName("formLayouTeam")
        self.labelTeamA = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTeamA.sizePolicy().hasHeightForWidth())
        self.labelTeamA.setSizePolicy(sizePolicy)
        self.labelTeamA.setMinimumSize(QtCore.QSize(50, 50))
        self.labelTeamA.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTeamA.setFont(font)
        self.labelTeamA.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTeamA.setObjectName("labelTeamA")
        self.formLayouTeam.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTeamA)
        self.textBrowserTeamA = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamA.setMinimumSize(QtCore.QSize(400, 50))
        self.textBrowserTeamA.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowserTeamA.setFont(font)
        self.textBrowserTeamA.setObjectName("textBrowserTeamA")
        self.formLayouTeam.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textBrowserTeamA)
        self.labelTeamB = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTeamB.sizePolicy().hasHeightForWidth())
        self.labelTeamB.setSizePolicy(sizePolicy)
        self.labelTeamB.setMinimumSize(QtCore.QSize(50, 50))
        self.labelTeamB.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTeamB.setFont(font)
        self.labelTeamB.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTeamB.setObjectName("labelTeamB")
        self.formLayouTeam.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTeamB)
        self.textBrowserTeamB = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamB.setMinimumSize(QtCore.QSize(400, 50))
        self.textBrowserTeamB.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowserTeamB.setFont(font)
        self.textBrowserTeamB.setObjectName("textBrowserTeamB")
        self.formLayouTeam.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textBrowserTeamB)
        self.labelTeamC = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTeamC.sizePolicy().hasHeightForWidth())
        self.labelTeamC.setSizePolicy(sizePolicy)
        self.labelTeamC.setMinimumSize(QtCore.QSize(50, 50))
        self.labelTeamC.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTeamC.setFont(font)
        self.labelTeamC.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTeamC.setObjectName("labelTeamC")
        self.formLayouTeam.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelTeamC)
        self.textBrowserTeamC = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamC.setMinimumSize(QtCore.QSize(400, 50))
        self.textBrowserTeamC.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowserTeamC.setFont(font)
        self.textBrowserTeamC.setObjectName("textBrowserTeamC")
        self.formLayouTeam.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textBrowserTeamC)
        self.labelTeamD = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTeamD.sizePolicy().hasHeightForWidth())
        self.labelTeamD.setSizePolicy(sizePolicy)
        self.labelTeamD.setMinimumSize(QtCore.QSize(50, 50))
        self.labelTeamD.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTeamD.setFont(font)
        self.labelTeamD.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTeamD.setObjectName("labelTeamD")
        self.formLayouTeam.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelTeamD)
        self.textBrowserTeamD = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamD.setMinimumSize(QtCore.QSize(400, 50))
        self.textBrowserTeamD.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowserTeamD.setFont(font)
        self.textBrowserTeamD.setObjectName("textBrowserTeamD")
        self.formLayouTeam.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textBrowserTeamD)
        self.labelTeamE = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTeamE.sizePolicy().hasHeightForWidth())
        self.labelTeamE.setSizePolicy(sizePolicy)
        self.labelTeamE.setMinimumSize(QtCore.QSize(50, 50))
        self.labelTeamE.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTeamE.setFont(font)
        self.labelTeamE.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTeamE.setObjectName("labelTeamE")
        self.formLayouTeam.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelTeamE)
        self.textBrowserTeamE = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamE.setMinimumSize(QtCore.QSize(400, 50))
        self.textBrowserTeamE.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowserTeamE.setFont(font)
        self.textBrowserTeamE.setObjectName("textBrowserTeamE")
        self.formLayouTeam.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textBrowserTeamE)
        self.gridLayoutWhole.addLayout(self.formLayouTeam, 1, 0, 1, 1)
        self.gridLayoutSplit = QtWidgets.QGridLayout()
        self.gridLayoutSplit.setObjectName("gridLayoutSplit")
        self.labelPickCard = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPickCard.sizePolicy().hasHeightForWidth())
        self.labelPickCard.setSizePolicy(sizePolicy)
        self.labelPickCard.setMinimumSize(QtCore.QSize(240, 324))
        self.labelPickCard.setMaximumSize(QtCore.QSize(240, 324))
        self.labelPickCard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelPickCard.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPickCard.setObjectName("labelPickCard")
        self.gridLayoutSplit.addWidget(self.labelPickCard, 0, 1, 2, 2)
        self.lineEditAthleteName = QtWidgets.QLineEdit(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAthleteName.sizePolicy().hasHeightForWidth())
        self.lineEditAthleteName.setSizePolicy(sizePolicy)
        self.lineEditAthleteName.setMinimumSize(QtCore.QSize(160, 70))
        self.lineEditAthleteName.setMaximumSize(QtCore.QSize(160, 70))
        self.lineEditAthleteName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditAthleteName.setObjectName("lineEditAthleteName")
        self.gridLayoutSplit.addWidget(self.lineEditAthleteName, 2, 0, 1, 2)
        self.pushButtonConfirm = QtWidgets.QPushButton(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonConfirm.sizePolicy().hasHeightForWidth())
        self.pushButtonConfirm.setSizePolicy(sizePolicy)
        self.pushButtonConfirm.setMinimumSize(QtCore.QSize(160, 90))
        self.pushButtonConfirm.setMaximumSize(QtCore.QSize(200, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonConfirm.setFont(font)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.gridLayoutSplit.addWidget(self.pushButtonConfirm, 2, 2, 1, 2)
        self.pushButtonStartWod = QtWidgets.QPushButton(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStartWod.sizePolicy().hasHeightForWidth())
        self.pushButtonStartWod.setSizePolicy(sizePolicy)
        self.pushButtonStartWod.setMinimumSize(QtCore.QSize(320, 90))
        self.pushButtonStartWod.setMaximumSize(QtCore.QSize(400, 90))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStartWod.setFont(font)
        self.pushButtonStartWod.setObjectName("pushButtonStartWod")
        self.gridLayoutSplit.addWidget(self.pushButtonStartWod, 3, 0, 1, 4)
        self.labelLeft = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLeft.sizePolicy().hasHeightForWidth())
        self.labelLeft.setSizePolicy(sizePolicy)
        self.labelLeft.setText("")
        self.labelLeft.setObjectName("labelLeft")
        self.gridLayoutSplit.addWidget(self.labelLeft, 0, 0, 2, 1)
        self.labelRight = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRight.sizePolicy().hasHeightForWidth())
        self.labelRight.setSizePolicy(sizePolicy)
        self.labelRight.setText("")
        self.labelRight.setObjectName("labelRight")
        self.gridLayoutSplit.addWidget(self.labelRight, 0, 3, 2, 1)
        self.gridLayoutWhole.addLayout(self.gridLayoutSplit, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayoutWhole, 0, 0, 1, 1)
        GroupSplitMainWindow.setCentralWidget(self.centralwidgetWhole)

        self.labelTeamA.setVisible(bool(self.teamConfigValue[0]))
        self.labelTeamB.setVisible(bool(self.teamConfigValue[1]))
        self.labelTeamC.setVisible(bool(self.teamConfigValue[2]))
        self.labelTeamD.setVisible(bool(self.teamConfigValue[3]))
        self.labelTeamE.setVisible(bool(self.teamConfigValue[4]))
        self.textBrowserTeamA.setVisible(bool(self.teamConfigValue[0]))
        self.textBrowserTeamB.setVisible(bool(self.teamConfigValue[1]))
        self.textBrowserTeamC.setVisible(bool(self.teamConfigValue[2]))
        self.textBrowserTeamD.setVisible(bool(self.teamConfigValue[3]))
        self.textBrowserTeamE.setVisible(bool(self.teamConfigValue[4]))

        if self.group < 5:
            self.pushButtonConfirm.clicked.connect(self.pickCard)
        else:
            self.pushButtonConfirm.clicked.connect(self.setEveryName)

        self.pushButtonStartWod.clicked.connect(self.goWodLoop)

        self.retranslateUi(GroupSplitMainWindow)
        QtCore.QMetaObject.connectSlotsByName(GroupSplitMainWindow)

    def retranslateUi(self, GroupSplitMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GroupSplitMainWindow.setWindowTitle(_translate("GroupSplitMainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("GroupSplitMainWindow", "抽签分组"))
        self.pushButtonConfirm.setText(_translate("GroupSplitMainWindow", "确认"))
        self.pushButtonStartWod.setText(_translate("GroupSplitMainWindow", "开始wod"))

        picPath = ":/Resources/PokerPictures/pokerBackBlue.png"
        pic = QtGui.QPixmap(picPath).scaled(self.labelPickCard.width(), self.labelPickCard.height())
        self.labelPickCard.setPixmap(pic)
        if self.group == 5:
            self.groupName = ['A', 'B', 'C', 'D', 'E']
        else:
            self.groupName = ['红桃', '黑桃', '草花', '方片', 'null']
        self.labelTeamA.setText(_translate("Dialog", self.groupName[0]))
        self.labelTeamB.setText(_translate("Dialog", self.groupName[1]))
        self.labelTeamC.setText(_translate("Dialog", self.groupName[2]))
        self.labelTeamD.setText(_translate("Dialog", self.groupName[3]))
        self.labelTeamE.setText(_translate("Dialog", self.groupName[4]))

    def goWodLoop(self):
        if (self.teamEveryNum[0] + self.teamEveryNum[1] + self.teamEveryNum[2] + self.teamEveryNum[3] + self.teamEveryNum[4]) != 0:
            QtWidgets.QMessageBox.information(self, '提示', '还有人没有找到队伍呢')
        else:
            self.configEveryTeamName()
            self.switch_window_WodLoop.emit(self.teamConfigValue, self.teamNameConfig, self.group)

    def goAthleteConfirm(self):
        self.switch_window_AthleteConfirm.emit(self.confirmAction, self.confirmBcardList)

    def pickCard(self):
        athleteName = self.lineEditAthleteName.text()
        if (self.teamEveryNum[0] + self.teamEveryNum[1] + self.teamEveryNum[2] + self.teamEveryNum[3]) == 0:
            QtWidgets.QMessageBox.information(self, '提示', '人满了开始WOD吧')
        elif athleteName == '':
            QtWidgets.QMessageBox.information(self, '提示', '你不能是无名氏哦')
        else:
            luckyDog = selectAthlete()
            picPath = ':/Resources/PokerPictures/' + luckyDog + '.png'
            pic = QtGui.QPixmap(picPath)
            self.labelPickCard.setPixmap(pic)
            self.labelPickCard.setScaledContents(True)

            if luckyDog == 'heart_A':
                heartText = self.textBrowserTeamA.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamA.setText(heartText)
                self.updateCurrentTeam(0, luckyDog)

            if luckyDog == 'spade_A':
                heartText = self.textBrowserTeamB.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamB.setText(heartText)
                self.updateCurrentTeam(1, luckyDog)

            if luckyDog == 'club_A':
                heartText = self.textBrowserTeamC.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamC.setText(heartText)
                self.updateCurrentTeam(2, luckyDog)

            if luckyDog == 'diamond_A':
                heartText = self.textBrowserTeamD.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamD.setText(heartText)
                self.updateCurrentTeam(3, luckyDog)
            # 每次输入后清空输入框
            self.lineEditAthleteName.clear()

    def setEveryName(self):
        athleteName = self.lineEditAthleteName.text()
        if self.groupTemp == 0:
            QtWidgets.QMessageBox.information(self, '提示', '人满了开始WOD吧')
        elif athleteName == '':
            QtWidgets.QMessageBox.information(self, '提示', '你不能是无名氏哦')
        else:
            athleteName = self.lineEditAthleteName.text()

            if self.groupTemp == 5:
                heartText = self.textBrowserTeamA.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamA.setText(heartText)
                self.updateCurrentTeam(0, '')

            if self.groupTemp == 4:
                heartText = self.textBrowserTeamB.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamB.setText(heartText)
                self.updateCurrentTeam(1, '')

            if self.groupTemp == 3:
                heartText = self.textBrowserTeamC.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamC.setText(heartText)
                self.updateCurrentTeam(2, '')

            if self.groupTemp == 2:
                heartText = self.textBrowserTeamD.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamD.setText(heartText)
                self.updateCurrentTeam(3, '')

            if self.groupTemp == 1:
                heartText = self.textBrowserTeamE.toPlainText()
                heartText = heartText + ' ' + athleteName
                self.textBrowserTeamE.setText(heartText)
                self.updateCurrentTeam(4, '')

            self.groupTemp = self.groupTemp - 1

            # 每次输入后清空输入框
            self.lineEditAthleteName.clear()

    def configEveryTeamName(self):
        self.teamNameConfig[0] = self.textBrowserTeamA.toPlainText()
        self.teamNameConfig[1] = self.textBrowserTeamB.toPlainText()
        self.teamNameConfig[2] = self.textBrowserTeamC.toPlainText()
        self.teamNameConfig[3] = self.textBrowserTeamD.toPlainText()
        self.teamNameConfig[4] = self.textBrowserTeamE.toPlainText()

    def updateCurrentTeam(self, pos, luckyDog):
        self.teamEveryNum[pos] -= 1
        if self.teamEveryNum[pos] == 0 and luckyDog != '':
            cardUpdateDeck(luckyDog)
