# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WodloopMainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5.QtCore import QTime, QTimer
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from LoteryWod import *
from modes import *


class Ui_WodLoopMainWindow(QtWidgets.QMainWindow):
    def __init__(self, team, teamName, group, confirmAction, confirmBcardList):
        super(Ui_WodLoopMainWindow, self).__init__()
        self.wodTime = QTime()
        self.wodTimer = QTimer()
        self.teamConfigValue = team
        self.teamNameConfig = teamName
        self.confirmAction = confirmAction
        self.confirmBcardList = confirmBcardList
        self.groupName = []
        self.group = group
        self.contDownTime = 10 * 1000  # 10sec
        self.round = 1
        self.ScoreA = 0
        self.ScoreB = 0
        self.ScoreC = 0
        self.ScoreD = 0
        self.ScoreE = 0
        self.setupUi(self)
        self.retranslateUi(self)
        # print(team, teamName, group, confirmAction, confirmBcardList)

    def setupUi(self, WodLoopMainWindow):
        WodLoopMainWindow.setObjectName("彩票机")
        WodLoopMainWindow.resize(844, 520)

        self.centralwidgetWhole = QtWidgets.QWidget(WodLoopMainWindow)
        self.centralwidgetWhole.setObjectName("centralwidgetWhole")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidgetWhole)
        self.gridLayout.setObjectName("gridLayout")
        self.labelTitle = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())

        self.wodTimer.timeout.connect(self.wodTimer_timeout)  # 定时器槽位

        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setMinimumSize(QtCore.QSize(820, 30))
        self.labelTitle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout.addWidget(self.labelTitle, 0, 0, 1, 2)
        self.gridLayoutTeam = QtWidgets.QGridLayout()
        self.gridLayoutTeam.setObjectName("gridLayoutTeam")
        self.pushButtonTeamA = QtWidgets.QPushButton(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTeamA.sizePolicy().hasHeightForWidth())
        self.pushButtonTeamA.setSizePolicy(sizePolicy)
        self.pushButtonTeamA.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonTeamA.setFont(font)
        self.pushButtonTeamA.setObjectName("pushButtonTeamA")
        self.gridLayoutTeam.addWidget(self.pushButtonTeamA, 0, 0, 1, 1)
        self.textBrowserTeamA = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserTeamA.sizePolicy().hasHeightForWidth())
        self.textBrowserTeamA.setSizePolicy(sizePolicy)
        self.textBrowserTeamA.setMinimumSize(QtCore.QSize(240, 40))
        self.textBrowserTeamA.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserTeamA.setObjectName("textBrowserTeamA")
        self.gridLayoutTeam.addWidget(self.textBrowserTeamA, 0, 1, 1, 1)
        self.buttonScoreA = QtWidgets.QPushButton(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buttonScoreA.setFont(font)
        self.buttonScoreA.setObjectName("buttonScoreA")
        self.gridLayoutTeam.addWidget(self.buttonScoreA, 0, 2, 1, 1)
        self.textBrowserScoreA = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserScoreA.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserScoreA.setObjectName("textBrowserScoreA")
        self.gridLayoutTeam.addWidget(self.textBrowserScoreA, 0, 3, 1, 1)
        self.pushButtonTeamB = QtWidgets.QPushButton(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTeamB.sizePolicy().hasHeightForWidth())
        self.pushButtonTeamB.setSizePolicy(sizePolicy)
        self.pushButtonTeamB.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonTeamB.setFont(font)
        self.pushButtonTeamB.setObjectName("pushButtonTeamB")
        self.gridLayoutTeam.addWidget(self.pushButtonTeamB, 1, 0, 1, 1)
        self.textBrowserTeamB = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamB.setMinimumSize(QtCore.QSize(240, 40))
        self.textBrowserTeamB.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserTeamB.setObjectName("textBrowserTeamB")
        self.gridLayoutTeam.addWidget(self.textBrowserTeamB, 1, 1, 1, 1)
        self.buttonScoreB = QtWidgets.QPushButton(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buttonScoreB.setFont(font)
        self.buttonScoreB.setObjectName("buttonScoreB")
        self.gridLayoutTeam.addWidget(self.buttonScoreB, 1, 2, 1, 1)
        self.textBrowserScoreB = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserScoreB.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserScoreB.setObjectName("textBrowserScoreB")
        self.gridLayoutTeam.addWidget(self.textBrowserScoreB, 1, 3, 1, 1)
        self.pushButtonTeamC = QtWidgets.QPushButton(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTeamC.sizePolicy().hasHeightForWidth())
        self.pushButtonTeamC.setSizePolicy(sizePolicy)
        self.pushButtonTeamC.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonTeamC.setFont(font)
        self.pushButtonTeamC.setObjectName("pushButtonTeamC")
        self.gridLayoutTeam.addWidget(self.pushButtonTeamC, 2, 0, 1, 1)
        self.textBrowserTeamC = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamC.setMinimumSize(QtCore.QSize(240, 40))
        self.textBrowserTeamC.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserTeamC.setObjectName("textBrowserTeamC")
        self.gridLayoutTeam.addWidget(self.textBrowserTeamC, 2, 1, 1, 1)
        self.buttonScoreC = QtWidgets.QPushButton(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buttonScoreC.setFont(font)
        self.buttonScoreC.setObjectName("buttonScoreC")
        self.gridLayoutTeam.addWidget(self.buttonScoreC, 2, 2, 1, 1)
        self.textBrowserScoreC = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserScoreC.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserScoreC.setObjectName("textBrowserScoreC")
        self.gridLayoutTeam.addWidget(self.textBrowserScoreC, 2, 3, 1, 1)
        self.textBrowserTeamD = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamD.setMinimumSize(QtCore.QSize(240, 40))
        self.textBrowserTeamD.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserTeamD.setObjectName("textBrowserTeamD")
        self.gridLayoutTeam.addWidget(self.textBrowserTeamD, 3, 1, 1, 1)
        self.buttonScoreD = QtWidgets.QPushButton(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buttonScoreD.setFont(font)
        self.buttonScoreD.setObjectName("buttonScoreD")
        self.gridLayoutTeam.addWidget(self.buttonScoreD, 3, 2, 1, 1)
        self.textBrowserScoreD = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserScoreD.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserScoreD.setObjectName("textBrowserScoreD")
        self.gridLayoutTeam.addWidget(self.textBrowserScoreD, 3, 3, 1, 1)
        self.pushButtonTeamE = QtWidgets.QPushButton(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTeamE.sizePolicy().hasHeightForWidth())
        self.pushButtonTeamE.setSizePolicy(sizePolicy)
        self.pushButtonTeamE.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonTeamE.setFont(font)
        self.pushButtonTeamE.setObjectName("pushButtonTeamE")
        self.gridLayoutTeam.addWidget(self.pushButtonTeamE, 4, 0, 1, 1)
        self.textBrowserTeamE = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserTeamE.setMinimumSize(QtCore.QSize(240, 40))
        self.textBrowserTeamE.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserTeamE.setObjectName("textBrowserTeamE")
        self.gridLayoutTeam.addWidget(self.textBrowserTeamE, 4, 1, 1, 1)
        self.buttonScoreE = QtWidgets.QPushButton(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buttonScoreE.setFont(font)
        self.buttonScoreE.setObjectName("buttonScoreE")
        self.gridLayoutTeam.addWidget(self.buttonScoreE, 4, 2, 1, 1)
        self.textBrowserScoreE = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserScoreE.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowserScoreE.setObjectName("textBrowserScoreE")
        self.gridLayoutTeam.addWidget(self.textBrowserScoreE, 4, 3, 1, 1)
        self.pushButtonTeamD = QtWidgets.QPushButton(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTeamD.sizePolicy().hasHeightForWidth())
        self.pushButtonTeamD.setSizePolicy(sizePolicy)
        self.pushButtonTeamD.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonTeamD.setFont(font)
        self.pushButtonTeamD.setObjectName("pushButtonTeamD")
        self.gridLayoutTeam.addWidget(self.pushButtonTeamD, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutTeam, 1, 0, 1, 1)
        self.gridLayoutCard = QtWidgets.QGridLayout()
        self.gridLayoutCard.setObjectName("gridLayoutCard")

        self.pushButtonPickCard = QtWidgets.QPushButton(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPickCard.sizePolicy().hasHeightForWidth())
        self.pushButtonPickCard.setSizePolicy(sizePolicy)
        self.pushButtonPickCard.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonPickCard.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonPickCard.setFont(font)
        self.pushButtonPickCard.setObjectName("pushButtonPickCard")
        self.gridLayoutCard.addWidget(self.pushButtonPickCard, 2, 0, 1, 2)
        self.labelCardB = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCardB.sizePolicy().hasHeightForWidth())
        self.labelCardB.setSizePolicy(sizePolicy)
        self.labelCardB.setMinimumSize(QtCore.QSize(180, 240))
        self.labelCardB.setMaximumSize(QtCore.QSize(360, 480))
        self.labelCardB.setObjectName("labelCardB")
        self.gridLayoutCard.addWidget(self.labelCardB, 0, 1, 1, 1)
        self.textBrowserWodB = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserWodB.setMinimumSize(QtCore.QSize(180, 40))
        self.textBrowserWodB.setMaximumSize(QtCore.QSize(360, 40))
        self.textBrowserWodB.setObjectName("textBrowserWodB")
        self.gridLayoutCard.addWidget(self.textBrowserWodB, 1, 1, 1, 1)
        self.textBrowserWodA = QtWidgets.QTextBrowser(self.centralwidgetWhole)
        self.textBrowserWodA.setMinimumSize(QtCore.QSize(180, 40))
        self.textBrowserWodA.setMaximumSize(QtCore.QSize(360, 40))
        self.textBrowserWodA.setObjectName("textBrowserWodA")
        self.gridLayoutCard.addWidget(self.textBrowserWodA, 1, 0, 1, 1)
        self.labelCardA = QtWidgets.QLabel(self.centralwidgetWhole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCardA.sizePolicy().hasHeightForWidth())
        self.labelCardA.setSizePolicy(sizePolicy)
        self.labelCardA.setMinimumSize(QtCore.QSize(180, 240))
        self.labelCardA.setMaximumSize(QtCore.QSize(360, 480))
        self.labelCardA.setObjectName("labelCardA")
        self.gridLayoutCard.addWidget(self.labelCardA, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutCard, 1, 1, 1, 1)

        # pickCard触发抽取wod的事件
        self.pushButtonPickCard.clicked.connect(self.pickWodJudge)

        self.horizontalLayoutTimer = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTimer.setObjectName("horizontalLayoutTimer")
        self.lcdNumberMin = QtWidgets.QLCDNumber(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lcdNumberMin.setFont(font)
        self.lcdNumberMin.setObjectName("lcdNumberMin")
        self.horizontalLayoutTimer.addWidget(self.lcdNumberMin)
        self.labelMin = QtWidgets.QLabel(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.labelMin.setFont(font)
        self.labelMin.setObjectName("labelMin")
        self.horizontalLayoutTimer.addWidget(self.labelMin)
        self.lcdNumberSec = QtWidgets.QLCDNumber(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lcdNumberSec.setFont(font)
        self.lcdNumberSec.setObjectName("lcdNumberSec")
        self.horizontalLayoutTimer.addWidget(self.lcdNumberSec)
        self.labelSec = QtWidgets.QLabel(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.labelSec.setFont(font)
        self.labelSec.setObjectName("labelSec")
        self.horizontalLayoutTimer.addWidget(self.labelSec)
        self.lcdNumberMSec = QtWidgets.QLCDNumber(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lcdNumberMSec.setFont(font)
        self.lcdNumberMSec.setObjectName("lcdNumberMSec")
        self.horizontalLayoutTimer.addWidget(self.lcdNumberMSec)
        self.labelMSec = QtWidgets.QLabel(self.centralwidgetWhole)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.labelMSec.setFont(font)
        self.labelMSec.setObjectName("labelMSec")
        self.horizontalLayoutTimer.addWidget(self.labelMSec)
        self.pushButtonStartTimer = QtWidgets.QPushButton(self.centralwidgetWhole)
        self.pushButtonStartTimer.setMinimumSize(QtCore.QSize(80, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStartTimer.setFont(font)
        self.pushButtonStartTimer.setObjectName("pushButtonStartTimer")
        self.pushButtonStartTimer.clicked.connect(self.startWodTimer)
        self.horizontalLayoutTimer.addWidget(self.pushButtonStartTimer)
        self.gridLayout.addLayout(self.horizontalLayoutTimer, 2, 0, 1, 2)
        # 根据队伍的多少显示组件
        self.buttonScoreA.setVisible(bool(self.teamConfigValue[0]))
        self.buttonScoreB.setVisible(bool(self.teamConfigValue[1]))
        self.buttonScoreC.setVisible(bool(self.teamConfigValue[2]))
        self.buttonScoreD.setVisible(bool(self.teamConfigValue[3]))
        self.buttonScoreE.setVisible(bool(self.teamConfigValue[4]))
        self.pushButtonTeamA.setVisible(bool(self.teamConfigValue[0]))
        self.pushButtonTeamB.setVisible(bool(self.teamConfigValue[1]))
        self.pushButtonTeamC.setVisible(bool(self.teamConfigValue[2]))
        self.pushButtonTeamD.setVisible(bool(self.teamConfigValue[3]))
        self.pushButtonTeamE.setVisible(bool(self.teamConfigValue[4]))
        self.textBrowserTeamA.setVisible(bool(self.teamConfigValue[0]))
        self.textBrowserTeamB.setVisible(bool(self.teamConfigValue[1]))
        self.textBrowserTeamC.setVisible(bool(self.teamConfigValue[2]))
        self.textBrowserTeamD.setVisible(bool(self.teamConfigValue[3]))
        self.textBrowserTeamE.setVisible(bool(self.teamConfigValue[4]))
        self.textBrowserScoreA.setVisible(bool(self.teamConfigValue[0]))
        self.textBrowserScoreB.setVisible(bool(self.teamConfigValue[1]))
        self.textBrowserScoreC.setVisible(bool(self.teamConfigValue[2]))
        self.textBrowserScoreD.setVisible(bool(self.teamConfigValue[3]))
        self.textBrowserScoreE.setVisible(bool(self.teamConfigValue[4]))

        self.buttonScoreA.clicked.connect(lambda:self.scoreIncrease(1))
        self.buttonScoreB.clicked.connect(lambda:self.scoreIncrease(2))
        self.buttonScoreC.clicked.connect(lambda:self.scoreIncrease(3))
        self.buttonScoreD.clicked.connect(lambda:self.scoreIncrease(4))
        self.buttonScoreE.clicked.connect(lambda:self.scoreIncrease(5))

        WodLoopMainWindow.setCentralWidget(self.centralwidgetWhole)

        self.retranslateUi(WodLoopMainWindow)
        QtCore.QMetaObject.connectSlotsByName(WodLoopMainWindow)

    def retranslateUi(self, WodLoopMainWindow):
        _translate = QtCore.QCoreApplication.translate
        WodLoopMainWindow.setWindowTitle(_translate("WodLoopMainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("WodLoopMainWindow", "开始wod吧"))

        self.buttonScoreA.setText(_translate("WodLoopMainWindow", "分数"))
        self.buttonScoreB.setText(_translate("WodLoopMainWindow", "分数"))
        self.buttonScoreC.setText(_translate("WodLoopMainWindow", "分数"))
        self.buttonScoreD.setText(_translate("WodLoopMainWindow", "分数"))
        self.buttonScoreE.setText(_translate("WodLoopMainWindow", "分数"))

        self.pushButtonPickCard.setText(_translate("WodLoopMainWindow", "抽取本轮Wod"))
        self.labelCardB.setText(_translate("WodLoopMainWindow", "TextLabel"))
        self.labelCardA.setText(_translate("WodLoopMainWindow", "TextLabel"))

        self.labelMin.setText(_translate("WodLoopMainWindow", "分"))
        self.labelSec.setText(_translate("WodLoopMainWindow", "秒"))
        self.labelMSec.setText(_translate("WodLoopMainWindow", "毫秒"))
        self.pushButtonStartTimer.setText(_translate("WodLoopMainWindow", "开始计时"))

        # 根据分组设置每个组的名称
        if self.group == 5:
            self.groupName = ['A', 'B', 'C', 'D', 'E']
        else:
            self.groupName = ['红桃', '黑桃', '草花', '方片', 'null']
        self.pushButtonTeamA.setText(_translate("WodLoopMainWindow", self.groupName[0]))
        self.pushButtonTeamB.setText(_translate("WodLoopMainWindow", self.groupName[1]))
        self.pushButtonTeamC.setText(_translate("WodLoopMainWindow", self.groupName[2]))
        self.pushButtonTeamD.setText(_translate("WodLoopMainWindow", self.groupName[3]))
        self.pushButtonTeamE.setText(_translate("WodLoopMainWindow", self.groupName[4]))
        self.setEveryTeamName()
        self.initEveryTeamScore()

        # 设置初始的卡片背景
        picPathA = ':/Resources/PokerPictures/pokerBackRed.png'
        picPathB = ':/Resources/PokerPictures/pokerBackBlue.png'
        picA = QtGui.QPixmap(picPathA)
        picB = QtGui.QPixmap(picPathB)
        self.labelCardB.setPixmap(picA)
        self.labelCardA.setPixmap(picB)
        self.labelCardB.setScaledContents(True)
        self.labelCardA.setScaledContents(True)

    def scoreIncrease(self, team):
        if team == 1:
            self.ScoreA += 1
            self.textBrowserScoreA.setText(str(self.ScoreA))
        elif team == 2:
            self.ScoreB += 1
            self.textBrowserScoreB.setText(str(self.ScoreB))
        elif team == 3:
            self.ScoreC += 1
            self.textBrowserScoreC.setText(str(self.ScoreC))
        elif team == 4:
            self.ScoreD += 1
            self.textBrowserScoreD.setText(str(self.ScoreD))
        else:
            self.ScoreE += 1
            self.textBrowserScoreE.setText(str(self.ScoreE))

    def pickWodJudge(self):
        if self.round <= 5:
            self.pickWod()
        else:
            QtWidgets.QMessageBox.information(self, '提示', 'wod虽好不要贪杯啊')

    def pickWod(self):  # 抽取卡牌获取wod
        roundText = "当前是第" + str(self.round) + "轮WoD"
        self.labelTitle.setText(roundText)
        wodDeck = WodDeck()
        luckyWodList = modeA4Ui(wodDeck, self.round, self.confirmBcardList)
        luckyWodA = luckyWodList[0]
        luckyWodB = luckyWodList[1]
        # print("-----------------luckyWodA: ", luckyWodA)
        actionA = bindActionByCard(luckyWodA, self.confirmBcardList, self.confirmAction)
        # print("-----------------actionA: ", actionA)
        # print("-----------------luckyWodB: ", luckyWodB)
        actionB = bindActionByCard(luckyWodB, self.confirmBcardList, self.confirmAction)
        # print("-----------------actionB: ", actionB)
        self.textBrowserWodA.setText(actionA)
        self.textBrowserWodB.setText(actionB)
        picPathA = ':/Resources/PokerPictures/' + luckyWodA + '.png'
        picPathB = ':/Resources/PokerPictures/' + luckyWodB + '.png'
        picA = QtGui.QPixmap(picPathA)
        picB = QtGui.QPixmap(picPathB)
        self.labelCardA.setPixmap(picA)
        self.labelCardB.setPixmap(picB)
        self.labelCardA.setScaledContents(True)
        self.labelCardB.setScaledContents(True)
        # print("luckyWodA：" + luckyWodA + "luckyWodB：" + luckyWodB)
        # print("actionA：" + actionA + "actionB：" + actionB)
        self.round += 1
        return luckyWodA, luckyWodB

    def initEveryTeamScore(self):  # 初始化每个队伍的分数
        self.textBrowserScoreA.setText('0')
        self.textBrowserScoreB.setText('0')
        self.textBrowserScoreC.setText('0')
        self.textBrowserScoreD.setText('0')
        self.textBrowserScoreE.setText('0')

    def setEveryTeamName(self):  # 从分组中继承每个队伍中人员的名字
        self.textBrowserTeamA.setText(self.teamNameConfig[0])
        self.textBrowserTeamB.setText(self.teamNameConfig[1])
        self.textBrowserTeamC.setText(self.teamNameConfig[2])
        self.textBrowserTeamD.setText(self.teamNameConfig[3])
        self.textBrowserTeamE.setText(self.teamNameConfig[4])

    def startWodTimer(self):  # 启动计时器和定时器
        self.wodTime.start()
        self.wodTimer.start(1)

    def wodTimer_timeout(self):
        remainTime = self.contDownTime - self.wodTime.elapsed()
        if self.contDownTime == 10 * 1000 and remainTime == 0:
            self.contDownTime = 30 * 60 * 1000  # 30sec
            self.wodTime.restart()
            self.lcdNumberMSec.display(remainTime % 1000)
            self.lcdNumberSec.display((remainTime // 1000) % 60)
            self.lcdNumberMin.display((remainTime // 1000) // 60)
        elif self.contDownTime == 30 * 60 * 1000 and remainTime == 0:
            self.wodTimer.stop()
            self.lcdNumberMSec.display(0)
            self.lcdNumberSec.display(0)
            self.lcdNumberMin.display(0)
        else:
            self.lcdNumberMSec.display(remainTime % 1000)
            self.lcdNumberSec.display((remainTime // 1000) % 60)
            self.lcdNumberMin.display((remainTime // 1000) // 60)

# if __name__ == '__main__':
#     app = QApplication(sys.argv)
#     app.processEvents()  # 防止进程卡死
#     MainWindow = QMainWindow()
#     ui = Ui_WodLoopMainWindow([1, 0, 0, 0, 0], ['', ' 1', '', '', ''], 1,
#                            {'heart': '1', 'spade': '1', 'club': '11', 'diamond': '1', 'bonus': '1'}, [])
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
